### ISSUE TITLE
Unknown operation "killcursors"

### ISSUE THREAD

**Issue by alexandernst** [watson/mongotail#1]
```
2015-07-26 11:06:07.347 QUERY     [person] : {"type": {"$in": [2]}, "short_id": "3000000"}
2015-07-26 11:06:07.347 QUERY     [tag] : {}
2015-07-26 11:06:07.349 QUERY     [category] : {}
2015-07-26 11:06:07.351 QUERY     [size_chart] : {"deviser_id": "3000000", "type": 1}
2015-07-26 11:06:07.366 QUERY     [category] : {"$orderby": {"name.en-US": 1}, "$query": {"path": "/"}}
2015-07-26 11:06:08.799 QUERY     [size_chart] : {"type": 0, "categories": {"$in": ["fb3d0"]}}
2015-07-26 11:26:50.240 QUERY     [category] : {}
Mongotail EXCEPTION - Unknown operation "killcursors"
Dump: {"ns": "", "ts": ISODate("2015-07-26T11:26:50.240Z"), "op": "killcursors"}
Traceback (most recent call last):
  File "/usr/local/bin/mongotail", line 9, in <module>
    load_entry_point('mongotail==0.3.2', 'console_scripts', 'mongotail')()
  File "/usr/local/lib/python2.7/dist-packages/mongotail/mongotail.py", line 156, in main
    tail(client, db, args.n, args.follow)
  File "/usr/local/lib/python2.7/dist-packages/mongotail/mongotail.py", line 68, in tail
    print_obj(result)
  File "/usr/local/lib/python2.7/dist-packages/mongotail/out.py", line 129, in print_obj
    operation.upper().ljust(9), doc, query))
UnboundLocalError: local variable 'query' referenced before assignment
```

**Comment by alexandernst** [comment]
After upgrading to latest version:

```
$ mongotail tests -l 2 
ERROR: Unexpected end of cursor

$ mongotail tests -f  
ERROR: Unexpected end of cursor
```

**Comment by watson** [comment]
@alexandernst Can it be that the capped collection you are trying to tail is empty? There is a limitation in relation to the way the node-driver for MongoDB tails collections that means that the cursor will end if the collection is empty (I think it's fixed upstream here: https://jira.mongodb.org/browse/NODE-435).

Try to add a document to the collection before tailing and/or let me know if this is your issue or not.

P.S. I've just added [a note](https://github.com/watson/mongotail#gotcha) about this gotcha to the README.md

**Comment by alexandernst** [comment]
@watson No, the database is not empty. It has several collections and each collections has ~20 documents.

**Comment by watson** [comment]
@alexandernst which version of MongoDB are you running?

**Comment by alexandernst** [comment]
@watson 3.0.4, Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49

**Comment by watson** [comment]
@alexandernst Are you sure this is the right repo to file this issue? I just took a second look at your command and it looks like a python module?! This is a node.js module

**Comment by alexandernst** [comment]
@watson Oops! Indeed. I'm sorry, it's just that your repo showed first when googling "mongotail" :)
So, this is actually your fault for making your repo appear in the first result in Google :D

**Comment by watson** [comment]
Sorry :wink:
